version: "3"

services:
  rabbit:
    image: rabbitmq:3-management
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
    ports:
      - "${RABBITMQ_EXPOSE_PORT}:5672"
      - "${RABBITMQ_MANAGEMENT_EXPOSE_PORT}:15672"
    logging:
      driver: "none"
  postgres:
    image: postgres:13
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_EXPOSE_PORT}:5432"

  redis:
    image: redis:6
    restart: always
    command: ["redis-server", "--appendonly", "yes"]
    hostname: redis
    volumes:
      - ./data/redis-data:/data
    ports:
      - ${REDIS_EXPOSE_PORT}:6379
    logging:
      driver: "none"

  flower:
    image: mher/flower
    command:
      [
        "celery",
        "flower",
        "--broker=amqp://${RABBITMQ_DEFAULT_USER}:${RABBITMQ_DEFAULT_PASS}@rabbit:5672",
        "--port=8888",
      ]
    ports:
      - ${FLOWER_EXPOSE_PORT}:8888
    logging:
      driver: "none"
    restart: always

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    volumes:
      - ./data/pgadmin:/root/.pgadmin
    ports:
      - "${PGADMIN_PORT}:80"
    logging:
      driver: none
    restart: always