version: '3'

services:
  rabbit:
    hostname: rabbit
    image: rabbitmq:3-management
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
    ports:
      - "${RABBITMQ_EXPOSE_PORT}:5672"
      - "${RABBITMQ_MANAGEMENT_EXPOSE_PORT}:15672"

  postgres:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_DEFAULT_USER}
      - POSTGRES_PASSWORD=${POSTGRES_DEFAULT_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DEFAULT_DB}
      - POSTGRES_PORT=${POSTGRES_DEFAULT_PORT}
    volumes:
      - ./data/postgres:/var/lib/postgresql/data

  redis:
    image: redis
    command: ["redis-server", "--appendonly", "yes"]
    hostname: redis
    volumes:
      - ./data/redis-data:/data

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    volumes:
       - ./data/pgadmin:/root/.pgadmin
    ports:
      - "${PGADMIN_PORT}:80"
    logging:
      driver: none
    restart: unless-stopped
  
  flower:
    image: mher/flower
    command: ["celery", "flower", "--broker=amqp://${RABBITMQ_DEFAULT_USER}:${RABBITMQ_DEFAULT_PASS}@rabbit:5672", "--port=8888"]  
    ports:  
      - ${FLOWER_EXPOSE_PORT}:8888

  web:
    build: .
    volumes:
      - .:/app
    ports:
      - "${WEB_HOST}:${WEB_HOST}"
    depends_on:
      - postgres
      - redis
    command: python manage.py runserver 0.0.0.0:${WEB_HOST}
  
  worker:
    build: .
    command: watchmedo auto-restart --recursive -p '*.py' -- python -m celery -A base worker --beat -l info
    volumes:
      - .:/app
    depends_on:
      - web
